
cloud:
 aws:
  credentials:
    access-key: AKIAQBA5CTQZLRQH26NW
    secret-key: 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
  region:  
    static: ap-south-1
  stack:  
    auto: false
    
applicaton:        
 bucket:
  name: omclinicbucket
  
spring:  
 servlet:
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
      max-file-size:
      max-request-size:
        


server:
  port: 8080        